#!/bin/bash
function GetRemotePs() {
  path=$1
  ret=""
  scp -rpP 62534 force-remote-worker $path:/home/fil/force-remote-worker1
ssh -p 62534 $path > /dev/null 2>&1 << eeooff
  cd /home/fil
  ls -l /home/fil/force-remote-worker > /home/fil/1.txt
  rm /home/fil/force-remote-worker
  mv /home/fil/force-remote-worker1 /home/fil/force-remote-worker
  rm /home/fil/force-remote-worker1
  ls -l  /home/fil/force-remote-worker  >> /home/fil/1.txt
  ret=`cat /home/fil/1.txt`
  exit
eeooff

  scp -rpP 62534 ${path}:/home/fil/1.txt ${path}.txt 
  ret=`cat ${path}.txt`
  echo $ret 
}

ipsi=(
"10.10.11.33" 
"10.10.11.34"
"10.10.11.35"
"10.10.11.36"
"10.10.11.37"
"10.10.11.38"
"10.10.11.39"
"10.10.11.40"
)

ips=(
"10.10.10.21" 
)

for ip in ${ips[@]}; do
  echo -e $ip
  ret=$(GetRemotePs $ip)
  # echo $ret
  cat ${ip}.txt

done
