#! /bin/bash
# 部署一个机会
# lotusip=10.10.10.206
# sealerip=10.10.10.207

amdip="10.10.10.206"
sealerip="10.10.10.206"
p23ip="10.10.10.207 10.10.10.208 10.10.10.209 10.10.10.210"
p23iparr=(10.10.10.207 10.10.10.208 10.10.10.209 10.10.10.210)
p4ip="10.10.10.211 10.10.10.212 10.10.10.213 10.10.10.214 10.10.10.215"
p4iparr=(10.10.10.211 10.10.10.212 10.10.10.213 10.10.10.214 10.10.10.215)

versionbasepath="/home/zhenglun/version"
cmdpath="/home/zhenglun/cmd"
forceconfigpath="/home/zhenglun/cmd/forceconfig"
versionpath="/home/zhenglun/version/20200627/version"

# ansible "$p23ip" -m shell -a "ps aux | grep force"
# ansible "$lotusip" -m copy -a "src=${versionpath}/lotus dest=/home/fil/ owner=fil group=fil"
# ansible "$lotusip" -m copy -a "src=${versionpath}/lotus-server dest=/home/fil/ owner=fil group=fil"
# ansible "$lotusip" -m copy -a "src=${versionpath}/lotus-storage-miner dest=/home/fil/ owner=fil group=fil"
# ansible "$lotusip" -m shell -a "chmod a+x *"
# ansible "$sealerip" -m copy -a "src=${versionpath}/lotus-storage-miner dest=/home/fil/ owner=fil group=fil"


# copsy force worker config.toml
ansible "$amdip" -m copy -a "src=${forceconfigpath}/${amdip}-p1config.toml dest=/home/fil/config.toml owner=fil group=fil"

for p23ipi in ${p23iparr[@]}; do
  echo $p23ipi
  ansible "$p23ipi" -m copy -a "src=${forceconfigpath}/${p23ipi}-p23config.toml dest=/home/fil/config.toml owner=fil group=fil"
done

for p4ipi in ${p4iparr[@]}; do
  echo $p4ipi
  ansible "$p4ipi" -m copy -a "src=${forceconfigpath}/${p4ipi}-p4config.toml dest=/home/fil/config.toml owner=fil group=fil"
done

# ansible "$p4ip" -m copy -a "src=${versionbasepath}/p4config.toml dest=/home/fil/config.toml owner=fil group=fil"

# copy force worker
ansible "$amdip" -m copy -a "src=${versionpath}/amd/force-remote-worker dest=/home/fil/ owner=fil group=fil"
ansible "$p23ip $p4ip" -m copy -a "src=${versionpath}/intel/force-remote-worker dest=/home/fil/ owner=fil group=fil"

# copy restartprocess
ansible "$amdip $p23ip $p4ip" -m copy -a "src=${cmdpath}/restartprocess dest=/home/fil/ owner=fil group=fil"
ansible "$amdip $p23ip $p4ip" -m copy -a "src=${cmdpath}/startprocess dest=/home/fil/ owner=fil group=fil"


ansible "$amdip $p23ip $p4ip"  -m shell -a "chmod a+x *"
