#!/bin/bash
datestr=$(date +%Y%m%d%H%M)
destdir="/home/zhenglun/log/$datestr"
mkdir $destdir 

lotusip="10.10.11.31"
sealerip="10.10.11.32"

p1pcip="10.10.10.21"
p23ip="10.10.11.33"
p4ip="10.10.11.37"

scp -rpP 62534 $lotusip":/home/fil/lotus.log" $destdir
scp -rpP 62534 $lotusip":/home/fil/poster.log"  $destdir
scp -rpP 62534 $sealerip":/home/fil/sealer.log" $destdir

scp -rpP 62534 $p1pcip":/home/fil/force-remote-worker.log" $destdir"/p1pc-"$p1pcip"-force-remote-worker.log"
scp -rpP 62534 $p23ip":/home/fil/force-remote-worker.log" $destdir"/p23-"$p23ip"-force-remote-worker.log"
scp -rpP 62534 $p4ip":/home/fil/force-remote-worker.log" $destdir"/p4-"$p4ip"-force-remote-worker.log"





