scheduler_url = "http://10.10.11.31:3456"
local_dir = "/sealer"
seal_commit_phase1_output = "/sealer/p3cache"
copy_limit_mb_per_sec = 500
group_id= [2]
sector_size = 536870912
ip = "10.10.10.214"

[[worker]]
num = 1
supported_phase = ["CommitPhase2"]
wait_sec = 60
